Draft for multi PVN support + protocol extension
Moresteck/Project-Poseidon-Uberbukkit pull request #32
Opened 2023-12-31 16:45 UTC by Moresteck

2023-12-31 17:04 UTC, notdevcody requested changes

2023-12-31 17:08 UTC, Moresteck commented on src/main/java/org/bukkit/craftbukkit/entity/CraftPlayer.java
> +    	if (pvn < 11 && message.equals("\u00A75\u00A76\u00A74\u00A75")) return;
It's not necessary to know what these are. It's the character sequence WorldEdit plugin greets the client with, for it to later communicate back with the plugin. The sequence crashes versions before b1.5, thus why it's being filtered out.

2023-12-31 17:10 UTC, Moresteck commented on src/main/java/net/minecraft/server/Packet62Sound.java
> +	public float f1;
`f` should be `volume`, and `f1` should become `pitch`, as per MCP mappings

2023-12-31 17:12 UTC, Moresteck commented on src/main/java/net/minecraft/server/Packet2Handshake.java
> +    public boolean pvn11;
It's impossible to deduct the exact PVN by just reading this packet. We can only know the PVN range the client is in. What better name should the field have? Maybe `isPVN11OrHigher`? Doesn't look too good tbh.

2023-12-31 17:26 UTC, notdevcody approved these changes
LGTM

2024-01-04 22:59 UTC, notdevcody requested changes

2024-01-05 10:53 UTC, notdevcody requested changes

2024-01-05 12:03 UTC, notdevcody approved these changes
Looks like ready to merge.

2024-01-05 12:28 UTC, merged